[package]
name = "example_project_rocket"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mongodb = "2.4.0"
redis = "0.23.0"
rocket = "0.5.0-rc.3"
